In [41]:
#1.	找出list中第k个最大，最小值。max(data, k)，min(data, k)函数，使用for语句

import os
#def compare1():
#    i1 = max(listforcompare)
#    j1 = min(listforcompare)
#    print(i1,j1)
 #   print(listforcompare.index(i1),listforcompare.index(j1))
    
#if __name__ == "__main__":
 #   listforcompare = [1,2,3,4,5,2,4,8,9,13,4]
 #   compare1()
#用for循环的方法，想了想没写出来
#for item in listforcompare：
#    if item。。。
#我想遍历数组里每一个item进行相互比较，不知道怎么写

def imax(arr):
    max_num = 0
    for a in arr:
        if a > max_num:
            max_num = a
    return max_num

def imin(arr):
    min_arr = 0
    for a in arr:
        if a <= min_arr:
            min_arr = a
    return min_arr

if __name__ == "__main__":
    data = [1,0,3,4,5,2,4,8,9,13,4]
    print(imax(data))
    print(imin(data))
    


13
0


In [30]:
a = [99,88,77,66,1234,2234,3234]
b = 0
for i in a:
    if b < i:
        b = i
print(b)

3234


In [19]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [58]:
#2.	将字符串中的 “hello”替换为”nihao”
#str1 = "hello"
#str2 = str1.replace("hello","nihao")
#print(str2)
str1 = "hello"
str2 = "nihao"
str1 = [i for i in str2]
print(str1)

#这个给点儿提示。。。

    

['n', 'i', 'h', 'a', 'o']


In [55]:
help（replace）


SyntaxError: invalid character in identifier (<ipython-input-55-b0f4044f74b1>, line 1)

In [41]:
#用list表示二维矩阵,并修改
import numpy as np
matrix = [[1,2,3],[4,5,6]]
print(matrix)
a = np.array([[1,2,3],[4,5,6]])
a[0][1]=5
a[0][2]=4
a[1][0]=3
a[1][1]=2
print(a)
#我用了最笨的方法。。。

[[1, 2, 3], [4, 5, 6]]
[[1 5 4]
 [3 2 6]]


In [1]:
#四个数字：1、2、3、4，能组成多少个互不相同且无重复数字的三位数？
#各是多少？
count=0
list1 = [1,2,3,4]
for i in list1:
    for j in list1:
        for k in list1:
            if(i!=j)and(j!=k)and(i!=k):
                print(i,j,k)
                count+=1
print(count)
#计数的这个不知道怎么写
            
            

1 2 3
1 2 4
1 3 2
1 3 4
1 4 2
1 4 3
2 1 3
2 1 4
2 3 1
2 3 4
2 4 1
2 4 3
3 1 2
3 1 4
3 2 1
3 2 4
3 4 1
3 4 2
4 1 2
4 1 3
4 2 1
4 2 3
4 3 1
4 3 2
24


In [81]:
#5二维矩阵乘法实现：multi(A, B)
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[1,2],[3,4]])
c = np.dot(a,b)
print(a,b)
print(c)

[[1 2 3]
 [4 5 6]] [[7 8]
 [1 2]
 [3 4]]
[[18 24]
 [51 66]]


In [99]:
#将data1-1，data1-2中的数据读出，转换成整型数据，
#作为两个二维矩阵A,B，显示
import csv
with open("F:\\ybclass\\first\\data1-1.csv") as file:
    reader = csv.reader(file)
    rows = [int(row) for row in reader]
    print(rows)
data = []
for l in open("F:\\ybclass\\first\\data1-2.txt"):
    row1 = [int(x) for x in l.split()]
    if len(row1) > 0:
        data.append(row1)
#读出来是字符串，转化成整型时报错

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [7]:
#还是上面那一题，发现了一个好用的库。。。
import pandas as pd
import numpy as np
a = pd.read_csv("F:\\ybclass\\first\\data1-1.csv")
print(a)
b = pd.read_table("F:\\ybclass\\first\\data1-2.txt")
print(b)
 
A = np.loadtxt(open("F:\\ybclass\\first\\data1-1.csv","rb"),delimiter=",",skiprows=0)
B = np.loadtxt(open("F:\\ybclass\\first\\data1-2.txt","rb"),delimiter=",",skiprows=0)
print(A)
print(B)
print(np.dot(A,B))
#最后还是numpy好用


   11   12   13  14
0  21    22  23  24
1  31    32  33  34
2  41    42  43  44
          51,52,53,54
0  61, 62,  63  ,  64
1   71,72, 73,74     
2      81,82,83,84   
[[ 11.  12.  13.  14.]
 [ 21.  22.  23.  24.]
 [ 31.  32.  33.  34.]
 [ 41.  42.  43.  44.]]
[[ 51.  52.  53.  54.]
 [ 61.  62.  63.  64.]
 [ 71.  72.  73.  74.]
 [ 81.  82.  83.  84.]]
[[  3350.   3400.   3450.   3500.]
 [  5990.   6080.   6170.   6260.]
 [  8630.   8760.   8890.   9020.]
 [ 11270.  11440.  11610.  11780.]]


In [30]:
#想弄明白数组和矩阵的区别。。
import numpy as np
a1 = np.array([1,1,1])
m1 = np.mat([[1,1,1],[1,2,3]])
#取矩阵中的元素只能用m1[1,2]
print(m1[1,2])
#将列表转换成矩阵
list1 = [[1,2],[4,5],[3,6]]
m2 = np.mat(list1)
m3 = np.dot(m1,m2)
#m3 = np.multiply(m1,m2) 这样乘起来报错，而用numpy里的点乘就可以
#为什么矩阵m1和m2不能相乘
print(a1)
print(m1)
print(m2)
print(m3)

3
[1 1 1]
[[1 1 1]
 [1 2 3]]
[[1 2]
 [4 5]
 [3 6]]
[[ 8 13]
 [18 30]]


In [56]:
#回到矩阵A和B上。
#newarray=delete(array,obg,axis)，obg是所要删除的行或列
#axis是要删除的维度，0表示行，1表示列（对于二维数组来说）
import numpy as np
A = np.loadtxt(open("F:\\ybclass\\first\\data1-1.csv","rb"),delimiter=",",skiprows=0)
B = np.loadtxt(open("F:\\ybclass\\first\\data1-2.txt","rb"),delimiter=",",skiprows=0)
A1 = np.delete(A,1,1)
B1 = np.delete(B,2,1)
C1 = A1 + B1
D = np.zeros([8,3])
print(A)
print(A1)
print(B1)
print(C1)
print(D)
#我觉得应该可以用一个循环将两个矩阵竖着叠加，我不太会写
Y = C1[:,2]
X = np.delete(C1,2,1)
print(X)


[[ 11.  12.  13.  14.]
 [ 21.  22.  23.  24.]
 [ 31.  32.  33.  34.]
 [ 41.  42.  43.  44.]]
[[ 11.  13.  14.]
 [ 21.  23.  24.]
 [ 31.  33.  34.]
 [ 41.  43.  44.]]
[[ 51.  52.  54.]
 [ 61.  62.  64.]
 [ 71.  72.  74.]
 [ 81.  82.  84.]]
[[  62.   65.   68.]
 [  82.   85.   88.]
 [ 102.  105.  108.]
 [ 122.  125.  128.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[  62.   65.]
 [  82.   85.]
 [ 102.  105.]
 [ 122.  125.]]


In [73]:
#11.实现一个Class，用于计算矩阵的加法、减法、乘法
import os
import numpy as np

class Matrix_cal(object):
    def __init__(self,matrix_A,matrix_B):
        self.matrix_A = matrix_A
        self.matrix_B = matrix_B
    
    def matrix_add(matrix_A,matrix_B):
        C = np.add(matrix_A,matrix_B)
        print(C)
    def matrix_dot(matrix_A,matrix_B):
        C = np.dot(matrix_A,matrix_B)
        print(C)
    def matrix_minus(matrix_A,matrix_B):
        C = np.minus(matrix_A,matrix_B)
        
if __name__ == "__main__":
    A = [[1,2,3],[4,5,6]]
    B = [[2,3,4],[7,8,9]]
    C = [[1,2],[3,4],[5,6]]
    A_add_B = Matrix_cal.matrix_add(A,B)
    A_dot_B = Matrix_cal.matrix_dot(A,C)
    A_minus_B = Matrix_cal.matrix_minus(A,B)

[[ 3  5  7]
 [11 13 15]]
[[22 28]
 [49 64]]


AttributeError: module 'numpy' has no attribute 'minus'